Update build.yaml

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -1,20 +1,16 @@
-name: Build
+name: Build and Test Project
 
 on:
   push:
     branches:
       - master
-  pull_request:
-    branches:
-      - master
 
 jobs:
   build:
-    name: Build and Test Project
+    name: Build and Test
     runs-on: ubuntu-latest
-
     steps:
-    - name: Checkout Main Project
+    - name: Checkout Repository
       uses: actions/checkout@v3
       
     - name: Set up JDK 17
@@ -22,20 +18,30 @@ jobs:
       with:
         distribution: 'temurin'
         java-version: '17'
-
-    - name: Clone JAR repository
-      run: |
-          git clone https://github.com/GuchievBashir/jar-repo jar-repo
-          mkdir -p libs
-          cp jar-repo/*.jar libs/
         
-    - name: Cache Maven dependencies
-      uses: actions/cache@v3
+    - name: Set up Python
+      uses: actions/setup-python@v3
       with:
-        path: ~/.m2
-        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
-        restore-keys: |
-          ${{ runner.os }}-maven-
-          
-    - name: Build with Maven
+        python-version: '3.8'
+
+    - name: Install Python Dependencies
+      run: |
+        pip install -r python-server/requirements.txt
+      
+    - name: Start Python Server
+      run: |
+        mkdir -p ./python-server/chords
+        nohup python3 python-server/server.py &
+      
+    - name: Build Java Project
       run: mvn clean install -DskipTests
+
+    - name: Run Java Application
+      run: java -cp target/GuitarUp-1.0.jar Main
+
+    - name: Check Chord Images
+      run: |
+        if [ ! -d ./python-server/chords ]; then
+          echo "Chord images not found!"
+          exit 1
+        fi
